# render.yaml
services:
  # 1. The Web Server (Your Django App)
  - type: web
    name: incubatoros-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn incubatoros.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4

  # 2. The Background Worker (For Celery Tasks)
  - type: worker
    name: incubatoros-celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A incubatoros worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: incubatoros-django
          envVarKey: SECRET_KEY

  # 3. The Message Broker (Redis for Celery)
  - type: pserv
    name: incubatoros-redis
    env: redis

# 4. The Database (PostgreSQL)
databases:
  - name: incubatoros-db
    databaseName: incubatoros
    user: incubator_user