# render.yaml (Bare-Bones Version)
services:
  # The Web Server (Your Django App)
  - type: web
    name: incubatoros-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn incubatoros.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4

# The PostgreSQL Database is the only other service needed
databases:
  - name: incubatoros-db
    databaseName: incubatoros
    user: incubator_user