# render.yaml (Simplified Version)
services:
  # 1. The Web Server (Your Django App)
  - type: web
    name: incubatoros-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn incubatoros.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: REDIS_URL 
        fromDatabase:
          name: incubatoros-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4

# All databases and services like Redis go here
databases:
  # The PostgreSQL Database
  - name: incubatoros-db
    databaseName: incubatoros
    user: incubator_user

  # The Redis Instance
  - name: incubatoros-redis
    plan: free