# render.yaml (Complete Version)
services:
  - type: web
    name: incubatoros-django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn incubatoros.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: incubatoros-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4

  - type: worker
    name: incubatoros-celery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A incubatoros worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: incubatoros-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: incubatoros-redis
          property: connectionString
      - key: SECRET_KEY
        fromService:
          type: web
          name: incubatoros-django
          envVarKey: SECRET_KEY

databases:
  - name: incubatoros-db
    databaseName: incubatoros
    user: incubator_user

  - name: incubatoros-redis
    plan: free