# Generated by Django 5.2.4 on 2025-07-28 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('founders', models.CharField(max_length=500)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('sector', models.CharField(max_length=100)),
                ('one_liner', models.TextField()),
                ('status', models.CharField(choices=[('PRE', 'Pre-Incubatee'), ('ASC', 'Associate Incubatee'), ('RSD', 'Resident Incubatee'), ('GRD', 'Graduated'), ('DRP', 'Dropped')], default='PRE', max_length=3)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('health_score', models.IntegerField(default=75, help_text='Calculated score 0-100')),
                ('is_at_risk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Recurring Revenue ($)')),
                ('active_users', models.IntegerField(default=0)),
                ('capital_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='core.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(help_text='Comma-separated values, e.g., Marketing, B2B Sales, Fundraising', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('assigned_companies', models.ManyToManyField(blank=True, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('Meeting', 'Meeting'), ('Email', 'Email'), ('Workshop', 'Workshop')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.company')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mentor')),
            ],
        ),
    ]
